### ISSUE TITLE
Preset Pins

### ISSUE THREAD

**Issue by Luke240** [jwetzell/q-sys-plugin-novastar#3]
I wanted to see if there's a way to have pins available for preset recalls.

**Comment by jwetzell** [comment]
This plugin already includes presets in the same way as the input switching is done. Is that not working?

**Comment by Luke240** [comment]
@jwetzell - This is great. Thank you. I'm using with a VX1000 and I have control so it's all good, but not sure if there's anything about the 1000 that is different.

**Comment by jwetzell** [comment]
Not sure. I've never had access to a NovaStar unit of any kind and there is no public documentation from NovaStar on how the control protocol works. But if it's working sounds good and I will close this issue.
